name: Deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - main  # 触发部署的分支是 main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read  # 允许读取代码
      pages: write    # 允许写入Pages
      id-token: write # 允许使用ID令牌认证[5](@ref)
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # 直接使用内置的GITHUB_TOKEN
          publish_dir: ./_site

